name: Deploy to github pages
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: build docs by vuepress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install npm dependencies
        run: yarn
      - name: build docs
        run: yarn docs:build
      - name: upload vuepress build result
        uses: actions/upload-artifact@v2
        with: 
          name: vuepress-dist
          path: docs/.vuepress/dist
  deploy:
    name: public to github pages
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: download previous build result
        uses: actions/download-artifact@v2
        with:
            name: vuepress-dist
      - name: view artifact files
        run: ls
      - run: git config --local user.name "longshihui"
      - run: git config --local user.email "391424924@qq.com"
      - run: git init
      - run: git add .
      - run: git commit -m "发布博客"
      - run: git push -f git@github.com:longshihui/blog.git master:gh-pages